let placessToVisit:string[]=["New York","Paris","Jakarta","Sydney","London","Adelaide","Islamabad"];
 console.log("Original Order:",placessToVisit);
 console.log("Alphabetical Order: ",[...placessToVisit].sort());
 console.log("Original Order:",placessToVisit);
 console.log("Reversed Alphabetical Order:",[...placessToVisit].sort().reverse());
 console.log("Original Order:",placessToVisit);
 console.log("Reversed Order:",placessToVisit.reverse());
 //console.log("Original Order:",placesToVisit);
 console.log("Original Order:",placessToVisit.reverse());
 //console.log("Original Order:",placesToVisit);
 console.log("Alphabetical Order: ",placessToVisit.sort());
 //console.log("Order Changed: ",placesToVisit);
 console.log("Reversed Alphabatical Order: ",placessToVisit.sort().reverse());